//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAST.Types {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class naturalFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal naturalFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FAST.Types.naturalFormats", typeof(naturalFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        internal static string FileSizeFormatProvider_bytes {
            get {
                return ResourceManager.GetString("FileSizeFormatProvider_bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string FileSizeFormatProvider_GB {
            get {
                return ResourceManager.GetString("FileSizeFormatProvider_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string FileSizeFormatProvider_KB {
            get {
                return ResourceManager.GetString("FileSizeFormatProvider_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string FileSizeFormatProvider_MB {
            get {
                return ResourceManager.GetString("FileSizeFormatProvider_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string FileSizeFormatProvider_TB {
            get {
                return ResourceManager.GetString("FileSizeFormatProvider_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        internal static string FriendlyDate_1_hour_ago {
            get {
                return ResourceManager.GetString("FriendlyDate_1_hour_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        internal static string FriendlyDateTime_1_minute_ago {
            get {
                return ResourceManager.GetString("FriendlyDateTime_1_minute_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string FriendlyDateTime_days_ago {
            get {
                return ResourceManager.GetString("FriendlyDateTime_days_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string FriendlyDateTime_hours_ago {
            get {
                return ResourceManager.GetString("FriendlyDateTime_hours_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} days.
        /// </summary>
        internal static string FriendlyDateTime_in_days {
            get {
                return ResourceManager.GetString("FriendlyDateTime_in_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} hours.
        /// </summary>
        internal static string FriendlyDateTime_in_hours {
            get {
                return ResourceManager.GetString("FriendlyDateTime_in_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} minutes.
        /// </summary>
        internal static string FriendlyDateTime_in_minutes {
            get {
                return ResourceManager.GetString("FriendlyDateTime_in_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} months.
        /// </summary>
        internal static string FriendlyDateTime_in_months {
            get {
                return ResourceManager.GetString("FriendlyDateTime_in_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} weeks.
        /// </summary>
        internal static string FriendlyDateTime_in_weeks {
            get {
                return ResourceManager.GetString("FriendlyDateTime_in_weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        internal static string FriendlyDateTime_just_now {
            get {
                return ResourceManager.GetString("FriendlyDateTime_just_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string FriendlyDateTime_minutes_ago {
            get {
                return ResourceManager.GetString("FriendlyDateTime_minutes_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        internal static string FriendlyDateTime_months_ago {
            get {
                return ResourceManager.GetString("FriendlyDateTime_months_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in an hour.
        /// </summary>
        internal static string FriendlyDateTime_next_hour {
            get {
                return ResourceManager.GetString("FriendlyDateTime_next_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in a minute.
        /// </summary>
        internal static string FriendlyDateTime_next_minute {
            get {
                return ResourceManager.GetString("FriendlyDateTime_next_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in a month.
        /// </summary>
        internal static string FriendlyDateTime_next_month {
            get {
                return ResourceManager.GetString("FriendlyDateTime_next_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month ago.
        /// </summary>
        internal static string FriendlyDateTime_one_month_ago {
            get {
                return ResourceManager.GetString("FriendlyDateTime_one_month_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        internal static string FriendlyDateTime_tomorrow {
            get {
                return ResourceManager.GetString("FriendlyDateTime_tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        internal static string FriendlyDateTime_weeks_ago {
            get {
                return ResourceManager.GetString("FriendlyDateTime_weeks_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string FriendlyDateTime_yesterday {
            get {
                return ResourceManager.GetString("FriendlyDateTime_yesterday", resourceCulture);
            }
        }
    }
}
