name: Publish FAST.MinimalSDK as NuGet Package

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.2.3
  workflow_dispatch: # Allows manual trigger from the GitHub UI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:
            8.0.x
            9.0.x
            
      - name: Restore dependencies
        run: dotnet restore FAST.MinimalSDK/FAST.MinimalSDK.csproj

      - name: Build project
        run: dotnet build FAST.MinimalSDK/FAST.MinimalSDK.csproj --configuration Release --no-restore 

      - name: Pack NuGet package
        run: dotnet pack FAST.MinimalSDK/FAST.MinimalSDK.csproj --configuration Release --no-build --output ./nuget 

      - name: Publish package to NuGet.org
        run: dotnet nuget push ./nuget/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}       


        
 
    
